apiVersion: v1
kind: Service
metadata:
  labels:
    name: ethereum
  name: ethereum
spec:
  ports:
    # The port that this service should serve on.
    - port: 8545
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    name: ethereum
