apiVersion: v1
kind: Pod
metadata:
  name: ethereum
  labels:
    name: ethereum
spec:
  containers:
    - resources:
        limits:
          cpu: 0.75
      image: ethereum/client-go:alpine
      name: ethereum
      args:
        - "--cache=768"
      env:
      ports:
        - containerPort: 8545
          name: ethereum
        - containerPort: 30303
          name: ethereum-peers
      volumeMounts:
          # This name must match the volumes.name below.
        - name: ethereum-blockchain-disk
          mountPath: /root/.ethereum/
  imagePullSecrets:
    - name: jeffregistrykey
  volumes:
    - name: ethereum-blockchain-disk
      gcePersistentDisk:
        # This disk must already exist.
        pdName: ethereum-blockchain-disk
        fsType: ext4
