apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
spec:
  containers:
    - resources:
        limits:
          cpu: 1
      image: TODO
      name: web
      args:
      env:
      ports:
        - containerPort: 80
          name: web
      volumeMounts:
  volumes:
