apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
spec:
  containers:
    - resources:
        limits:
          cpu: 0.5
      image: slapbassist-docker-tinypay-web.bintray.io/mustwin/tinypay-web:latest
      name: web
      args:
      env:
      ports:
        - containerPort: 80
          name: web
      volumeMounts:
      imagePullPolicy: Always
  imagePullSecrets:
      - name: jeffregistrykey
  volumes:
